[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/newsapi-proxy"
  status = 200 